name: armazemf
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0  
  cupertino_icons: ^1.0.6
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+2
  flutter_modular: ^5.0.3
  asuka: ^2.2.1
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.3
  pdf: ^3.10.8
  flutter_pdfview: ^1.3.2
  share_plus: ^7.0.2
  syncfusion_flutter_charts: ^21.2.4


  
dev_dependencies:
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.6+3
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - .env
